### ISSUE TITLE
t/Catmandu-Importer-BibTeX.t started to fail

### ISSUE THREAD

**Issue by eserte** [LibreCat/Catmandu-BibTeX#6]
My smoker systems started to report a new test failure:
```
# Failed test at t/Catmandu-Importer-BibTeX.t line 56.
# +------------+-------+----+--------+
# | PATH       | GOT   | OP | CHECK  |
# +------------+-------+----+--------+
# | [1]{pages} | 21–32 | eq | 21--32 |
# +------------+-------+----+--------+
# Seeded srand with seed '20210123' from local date.
t/Catmandu-Importer-BibTeX.t ... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
```

Juest a guess (not backed up by statistical analysis): this is caused by LaTeX-ToUnicode-0.11.

**Comment by eserte** [comment]
It's hard to spot: the dash in the "got" value is an EN DASH (unicode codepoint 0x2013), which seems to be the right replacement for a TeX "--".

**Comment by nics** [comment]
Reverting to LaTeX::ToUnicode 0.05 indeed fixes the test.

**Comment by eserte** [comment]
Please note that my smoker (and other CPAN.pm-based smokers) will still send fail reports --- CPAN.pm does not (rightly) handle anything but minimum version specifications, so the "== 0.05" spec won't work here. If you want to avoid getting fail reports you probably have to make the failing test into a conditional $TODO test.

**Comment by vpeil** [comment]
> Please note that my smoker (and other CPAN.pm-based smokers) will still send fail reports --- CPAN.pm does not (rightly) handle anything but minimum version specifications, so the "== 0.05" spec won't work here. If you want to avoid getting fail reports you probably have to make the failing test into a conditional $TODO test.

Thanks for this hint. That was exactly what I stumbled upon this morning.
