### ISSUE TITLE
carton cannot install version 0.19

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/Catmandu-BibTeX#8]
carton cannot install version 0.19 due to conflicting requirements:

* `Catmandu::BibTeX` requires exact version `0.05` of `LaTeX::ToUnicode`
* Dependency `BibTeX::Parser` requires `LaTeX::ToUnicode >= 0.11`

cf. https://github.com/LibreCat/Catmandu-BibTeX/blame/main/cpanfile
cf. https://metacpan.org/source/BORISV/BibTeX-Parser-1.03/Makefile.PL

Now LibreCat cannot be installed either..

**Comment by vpeil** [comment]
@nics provided vesion 0.20 some days ago. Does the new version solve your problem?
